# Generated by Django 5.2.7 on 2025-11-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image_main', models.ImageField(upload_to='products/')),
                ('images', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='product_audios/')),
            ],
        ),
    ]
