# Generated by Django 5.2.7 on 2025-11-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0003_rename_aka_flora_flora_aka_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='Audio',
            new_name='Story_Audio',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Image',
            new_name='Story_Image',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Title',
            new_name='Story_Title',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='Text',
            new_name='Story_text',
        ),
    ]
