# Generated by Django 5.2.7 on 2025-11-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0004_rename_audio_story_story_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='Bird_Question',
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Quiz_Correct',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Quiz_OptionA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Quiz_OptionB',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Quiz_OptionC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Quiz_OptionD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Quiz_Question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
