# Generated by Django 5.2.7 on 2025-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0005_remove_bird_bird_question_bird_bird_quiz_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='Bird_Buttton_Media',
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Button_Media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
