# Generated by Django 5.2.7 on 2025-11-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0006_remove_bird_bird_buttton_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='Bird_Button_Media',
        ),
        migrations.AddField(
            model_name='bird',
            name='Bird_Buttton_Media',
            field=models.FilePathField(blank=True, match='.*\\.(mp4|webm)$', max_length=255, null=True, path='static/video/Bird', recursive=True),
        ),
    ]
