# Generated by Django 5.2.7 on 2025-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0008_remove_bird_bird_buttton_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='Flora_Button_Media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
