# Generated by Django 5.2.7 on 2025-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0009_alter_flora_flora_button_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='Bird_Button_Thumb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
