# Generated by Django 5.2.7 on 2025-12-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0010_bird_bird_button_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Length_Details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Weight_Details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Wingspan_Details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
