# Generated by Django 5.2.7 on 2025-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0011_alter_bird_bird_length_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Lifespan_Details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
