# Generated by Django 5.2.7 on 2025-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0012_alter_bird_bird_lifespan_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='nature_trails/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='nature_trails/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
