# Generated by Django 5.2.7 on 2025-12-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0016_flora_flora_quiz_correct_flora_flora_quiz_optiona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='Flora_Family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='flora_images/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='flora_images/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='flora_images/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Media_1',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='flora_media/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Media_2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='flora_media/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Zones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
