# Generated by Django 5.2.7 on 2025-12-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0017_alter_flora_flora_family_alter_flora_flora_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Media_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Media_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
