# Generated by Django 5.2.7 on 2026-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0018_alter_flora_flora_image_1_alter_flora_flora_image_2_and_more'),
    ]

    operations = [
       migrations.AddField(
        model_name='bird',
        name='slug',
        field=models.SlugField(null=True, blank=True),
    ),

    ]
