# Generated by Django 5.2.7 on 2026-01-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0019_bird_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
