# Generated by Django 5.2.7 on 2026-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0020_alter_bird_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Image1',
            field=models.ImageField(upload_to='birds/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Image2',
            field=models.ImageField(blank=True, null=True, upload_to='birds/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Video',
            field=models.FileField(blank=True, null=True, upload_to='birds/videos/'),
        ),
    ]
