# Generated by Django 5.2.7 on 2026-01-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0021_alter_bird_bird_image1_alter_bird_bird_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Flora/'),
        ),
    ]
