# Generated by Django 5.2.7 on 2026-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0022_alter_flora_flora_image_1_alter_flora_flora_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Flora/'),
        ),
    ]
