# Generated by Django 5.2.7 on 2026-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0023_alter_flora_flora_image_1_alter_flora_flora_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='Bird_Image2',
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Image1',
            field=models.ImageField(upload_to='birds/Images'),
        ),
    ]
