# Generated by Django 5.2.7 on 2026-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0024_remove_bird_bird_image2_alter_bird_bird_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Image1',
            field=models.ImageField(blank=True, null=True, upload_to='birds/Images'),
        ),
    ]
