# Generated by Django 5.2.7 on 2026-01-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0026_alter_bird_bird_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='Bird_Poster',
            field=models.ImageField(blank=True, null=True, upload_to='birds/Images/Posters'),
        ),
    ]
