# Generated by Django 5.2.7 on 2026-02-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0027_bird_bird_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Animation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
