# Generated by Django 5.2.7 on 2026-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0028_alter_bird_bird_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Animation',
            field=models.FileField(blank=True, null=True, upload_to='Animations/Birds/Single Birds/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Button_Media',
            field=models.FileField(blank=True, null=True, upload_to='Animations/Birds/Buttons/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Button_Thumb',
            field=models.FileField(blank=True, null=True, upload_to='Animations/Birds/Single Birds/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Image1',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Birds/'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Poster',
            field=models.ImageField(blank=True, null=True, upload_to='Videos/Posters'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='Bird_Video',
            field=models.FileField(blank=True, null=True, upload_to='Videos/Birds/'),
        ),
    ]
