# Generated by Django 5.2.7 on 2026-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0029_alter_bird_bird_animation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flora',
            name='Flora_Button_Media',
            field=models.FileField(blank=True, null=True, upload_to='Animations/Flora/Buttons/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Flora/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Media_1',
            field=models.FileField(blank=True, null=True, upload_to='Animations/Flora/Single Plants/'),
        ),
        migrations.AlterField(
            model_name='flora',
            name='Flora_Media_2',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Illustrations/Trees/'),
        ),
    ]
