# Generated by Django 5.2.7 on 2026-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0030_alter_flora_flora_button_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='Bird_Call',
            field=models.FileField(blank=True, null=True, upload_to='Audio/Bird_Calls/'),
        ),
    ]
