# Generated by Django 5.2.7 on 2026-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0031_alter_bird_bird_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='BirdAt_HoHStatus',
            field=models.CharField(max_length=100),
        ),
    ]
