# Generated by Django 5.2.7 on 2026-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0032_alter_bird_birdat_hohstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='Bird_Videolink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
