# Generated by Django 5.2.7 on 2026-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0033_bird_bird_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturetrailschedule',
            name='day',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
