# Generated by Django 5.2.7 on 2026-02-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0034_alter_naturetrailschedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='Bird_Video',
        ),
    ]
