# Generated by Django 5.2.7 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0035_remove_bird_bird_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='Bird_Video',
            field=models.FileField(blank=True, null=True, upload_to='Videos/Birds/'),
        ),
    ]
