# Generated by Django 5.2.7 on 2026-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0036_bird_bird_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturetrailmedia',
            name='youtube_link',
            field=models.CharField(blank=True, help_text='Only YouTube Video ID (example: dQw4w9WgXcQ)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naturetrailmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='nature_trails/media/'),
        ),
    ]
