# Generated by Django 5.2.7 on 2026-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0037_naturetrailmedia_youtube_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='Bird_Map_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/bird_maps/'),
        ),
    ]
