# Generated by Django 5.2.7 on 2026-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0038_bird_bird_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flora',
            name='Flora_Map_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Imagesflora_maps/'),
        ),
    ]
