# Generated by Django 5.2.7 on 2026-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0039_flora_flora_map_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Butterfly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Butterfly_Scientific_Name', models.CharField(max_length=255)),
                ('Butterfly_Name', models.CharField(max_length=255)),
                ('Butterfly_AKA', models.TextField(blank=True, null=True)),
                ('Butterfly_Family', models.CharField(max_length=255)),
                ('Butterfly_Description', models.TextField()),
                ('Butterfly_Colour_Key', models.CharField(max_length=255)),
                ('Butterfly_Geographic_Range', models.TextField()),
                ('Butterfly_Zones', models.TextField()),
                ('Butterfly_Habitat', models.TextField()),
                ('Butterfly_Behaviour', models.TextField()),
                ('Butterfly_Nesting_Mating', models.TextField()),
                ('Butterfly_Feeding_Behaviour', models.TextField()),
                ('Butterfly_Migration', models.TextField()),
                ('Butterfly_Migration_Key', models.CharField(max_length=100)),
                ('Butterfly_Evolutionary_Adaptations', models.TextField()),
                ('Butterfly_Defence_Key', models.CharField(max_length=100)),
                ('Butterfly_Fun_Facts', models.TextField()),
                ('Butterfly_Lifespan', models.CharField(max_length=50)),
                ('Butterfly_Lifespan_Details', models.TextField(blank=True, null=True)),
                ('Butterfly_Length', models.CharField(max_length=50)),
                ('Butterfly_Length_Details', models.TextField(blank=True, null=True)),
                ('Butterfly_Wingspan_sort', models.IntegerField(default=0)),
                ('Butterfly_Wingspan', models.CharField(max_length=50)),
                ('Butterfly_Wingspan_Details', models.TextField(blank=True, null=True)),
                ('Butterfly_Weight', models.CharField(max_length=50)),
                ('Butterfly_Weight_Details', models.TextField(blank=True, null=True)),
                ('Butterfly_Conservation_Status', models.CharField(max_length=100)),
                ('Butterfly_Conservation_Status_SVGKey', models.CharField(max_length=20)),
                ('Butterfly_Conservation_Description', models.TextField()),
                ('Butterfly_Animation', models.FileField(blank=True, null=True, upload_to='Animations/Butterflies/Single Butterflies/')),
                ('Butterfly_Call', models.FileField(blank=True, null=True, upload_to='Audio/Butterfly_Calls/')),
                ('Butterfly_Video', models.FileField(blank=True, null=True, upload_to='Videos/Butterflies/')),
                ('Butterfly_Image1', models.ImageField(blank=True, null=True, upload_to='Images/Butterflies/')),
                ('Butterfly_Map_Image', models.ImageField(blank=True, null=True, upload_to='Images/butterfly_maps/')),
                ('Butterfly_Button_Media', models.FileField(blank=True, null=True, upload_to='Animations/Butterflies/Buttons/')),
                ('Butterfly_Button_Thumb', models.FileField(blank=True, null=True, upload_to='Animations/Butterflies/Single Butterflies/')),
                ('Butterfly_Quiz_Question', models.TextField(blank=True, null=True)),
                ('Butterfly_Quiz_OptionA', models.CharField(blank=True, max_length=255, null=True)),
                ('Butterfly_Quiz_OptionB', models.CharField(blank=True, max_length=255, null=True)),
                ('Butterfly_Quiz_OptionC', models.CharField(blank=True, max_length=255, null=True)),
                ('Butterfly_Quiz_OptionD', models.CharField(blank=True, max_length=255, null=True)),
                ('Butterfly_Quiz_Correct', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
