# Generated by Django 5.2.7 on 2026-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0040_butterfly'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterfly',
            name='Butterfly_Image2',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Butterflies/'),
        ),
        migrations.AlterField(
            model_name='butterfly',
            name='Butterfly_Map_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Imagesbutterfly_maps/'),
        ),
    ]
