# Generated by Django 5.2.7 on 2026-08-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eonapp', '0041_remove_butterfly_butterfly_call_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butterfly',
            name='Butterfly_Call',
        ),
        migrations.RemoveField(
            model_name='butterfly',
            name='Butterfly_Video',
        ),
    ]
